-- ================================================================
-- Trackrr: Supabase Database Schema & Row Level Security (RLS)
-- Run this script in your Supabase Project: SQL Editor -> New query
-- ================================================================

-- 1. Enable UUID extension
create extension if not exists "uuid-ossp";

-- 2. Workspaces Table
create table if not exists public.workspaces (
  id text primary key default uuid_generate_v4()::text,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  name text not null,
  color text default '#818CF8',
  created_at timestamptz default timezone('utc'::text, now()) not null,
  updated_at timestamptz default timezone('utc'::text, now()) not null
);

-- 3. Clients Table
create table if not exists public.clients (
  id text primary key default uuid_generate_v4()::text,
  workspace_id text references public.workspaces(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  name text not null,
  company text default '',
  email text default '',
  phone text default '',
  color text default '#818CF8',
  payment_type text default 'per_video' check (payment_type in ('per_video', 'monthly')),
  monthly_salary numeric default 0,
  notes text default '',
  created_at timestamptz default timezone('utc'::text, now()) not null,
  updated_at timestamptz default timezone('utc'::text, now()) not null
);

-- 4. Tasks Table
create table if not exists public.tasks (
  id text primary key default uuid_generate_v4()::text,
  workspace_id text references public.workspaces(id) on delete cascade not null,
  client_id text references public.clients(id) on delete set null,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  title text not null,
  description text default '',
  status text default 'Completed',
  videos integer default 1,
  price numeric default 0,
  pricing_type text default 'per_video' check (pricing_type in ('total', 'per_video')),
  received_date text not null,
  completed_date text,
  deadline text,
  tags text[] default '{}',
  order_index integer default 0,
  created_at timestamptz default timezone('utc'::text, now()) not null,
  updated_at timestamptz default timezone('utc'::text, now()) not null
);

-- 5. Salary Rates Table (for monthly retainer history)
create table if not exists public.salary_rates (
  id text primary key default uuid_generate_v4()::text,
  client_id text references public.clients(id) on delete cascade not null,
  workspace_id text references public.workspaces(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  amount numeric not null,
  effective_from text not null,
  created_at timestamptz default timezone('utc'::text, now()) not null
);

-- 6. Discounts Table
create table if not exists public.discounts (
  id text primary key default uuid_generate_v4()::text,
  client_id text references public.clients(id) on delete cascade not null,
  workspace_id text references public.workspaces(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  amount numeric not null,
  note text default '',
  date text not null,
  payment_for_months text[] default '{}',
  created_at timestamptz default timezone('utc'::text, now()) not null
);

-- 7. Payments Table
create table if not exists public.payments (
  id text primary key default uuid_generate_v4()::text,
  client_id text references public.clients(id) on delete cascade not null,
  workspace_id text references public.workspaces(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  amount numeric not null,
  method text default 'Cash',
  note text default '',
  date text not null,
  payment_for_months text[] default '{}',
  created_at timestamptz default timezone('utc'::text, now()) not null
);

-- 8. User Settings Table
create table if not exists public.settings (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid() unique,
  active_workspace_id text,
  currency text default 'USD' check (currency in ('USD', 'INR')),
  theme_color text default '#818CF8',
  show_completed boolean default true,
  updated_at timestamptz default timezone('utc'::text, now()) not null
);

-- ================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- Ensures users can only access their own workspaces and data
-- ================================================================

alter table public.workspaces enable row level security;
alter table public.clients enable row level security;
alter table public.tasks enable row level security;
alter table public.salary_rates enable row level security;
alter table public.discounts enable row level security;
alter table public.payments enable row level security;
alter table public.settings enable row level security;

-- Policies for workspaces
create policy "Users can manage own workspaces" on public.workspaces
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Policies for clients
create policy "Users can manage own clients" on public.clients
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Policies for tasks
create policy "Users can manage own tasks" on public.tasks
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Policies for salary_rates
create policy "Users can manage own salary rates" on public.salary_rates
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Policies for discounts
create policy "Users can manage own discounts" on public.discounts
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Policies for payments
create policy "Users can manage own payments" on public.payments
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Policies for settings
create policy "Users can manage own settings" on public.settings
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
